title: Come Follow Me
description: Jesus Lives
owner_name: John Mortensen
github_username: jm1021
github_repo: "churchofjesuschrist"
baseurl: "/churchofjesuschrist"
future: true
show_image: true
remote_theme: jekyll/minima
minima:
  nav_pages:
    - navigation/search.md
    - navigation/about.md
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders/teacher_portfolio"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" }      
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
